### ISSUE TITLE
Useless dependency

### ISSUE THREAD

**Issue by seaneble** [heimrichhannot/contao-member_plus#1]
There is a discrepancy between composer and the autoloader configuration:

https://github.com/heimrichhannot/contao-member_plus/blob/master/config/autoload.ini#L4
https://github.com/heimrichhannot/contao-member_plus/blob/master/composer.json#L21

I don't see any hard dependency of this module to contao-formhybrid, so I suggest you drop the require in composer.json. It leads to quite a lot of additional modules being installed, like extcss. If there is some kind of technical reason for this, I recommend moving the shared code to a common library used by both modules.

**Comment by fatcrobat** [comment]
Formhybrid dependency is required by member_plus registration plus module. But we removed the bootstrapper dependendy within heimrichhannot/contao-formhybrid#1

**Comment by seaneble** [comment]
Okay, I looked at it from the wrong side. But it still makes sense.
