### ISSUE TITLE
Contao 4.13 Php 8.0

### ISSUE THREAD

**Issue by JessesNei** [heimrichhannot/contao-member_plus#11]
I can not composer update to update my installation for Comntao 8.0 or 8.1 but on the requirements php 8.0 is listed as shown below:

`php~5.4 || ~7.0 || ^8.0`

Composer update error:

`  Problem 1
    - heimrichhannot/contao-fieldpalette[1.4.5, ..., 1.4.10] require php ~5.4 || ~7.0 -> your php version (8.0.29) does not satisfy that requirement.
    - heimrichhannot/contao-member_plus 2.3.0 requires heimrichhannot/contao-fieldpalette ^1.4.5 -> satisfiable by heimrichhannot/contao-fieldpalette[1.4.5, ..., 1.4.10].
    - Root composer.json requires heimrichhannot/contao-member_plus ^2.3 -> satisfiable by heimrichhannot/contao-member_plus[2.3.0].`

**Comment by koertho** [comment]
Hi, first of all please see the information from the readme!

> This bundle is abandoned and not actively maintained anymore. Please use https://github.com/heimrichhannot/contao-member-bundle.

In addition to that: Your composer issue is the same as in your last issue: https://github.com/heimrichhannot/contao-member_plus/issues/9
