### ISSUE TITLE
Empty image size leads to error

### ISSUE THREAD

**Issue by seaneble** [heimrichhannot/contao-member_plus#2]
Hello,

the backend displays the following error while viewing the list of content elements of an article, one of which is a memberlist:

```
Fatal error: Cannot unset string offsets in /…/system/modules/core/library/Contao/Controller.php on line 1478
```

This error is present unless one sets a width and height for the avatars. But those two fields are not mandatory, so every time a user creates a memberlist content element and does not specify a size, he encounters the error message upon "save and back".

**Comment by fatcrobat** [comment]
Cant reproduce, with fresh install of contao 3.5.2, what version are you using?
