### ISSUE TITLE
Kann im Modul Mitgliederleser keine Felder ausschließen

### ISSUE THREAD

**Issue by pointout** [heimrichhannot/contao-member_plus#3]
Contao 4.4.3
contao-member_plus 2.0.33

If I want to restrict the fields, that should be shown, the loading icon is hanging. Relaoding the page leads to following error:

```
Was ist das Problem?
Compile Error: Cannot declare class tl_content_member_plus, because the name is already in use
```
It's not possible to edit the modul again. Same error mesasage. I only can delete the module.

**Comment by fatcrobat** [comment]
Hi, installed member_plus this moment in contao `managed-edition`, created `memberreader` module and can edit `mlSkipFields`. Anyways, for the moment copied `getViewableMemberFields` function from `tl_content_member_plus` to `tl_module_member_plus`. Should be fixed in `2.0.36`, deployed soon.
