### ISSUE TITLE
Composer "no matching package found"

### ISSUE THREAD

**Issue by GMTeams** [heimrichhannot/contao-member_plus#4]
Trying to install it via Composer (ssh):

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for heimrichhannot/contao-member_plus >=2.0.36.0,<2.1-dev -> satisfiable by heimrichhannot/contao-member_plus[2.0.36].
    - heimrichhannot/contao-member_plus 2.0.36 requires heimrichhannot/contao-bootstrapper >=1.14.13,<2.0.0-dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.`

Settings:
Contao: 3.5.25
Minimale Stabilität: Entwicklerversion
"Stabil bevorzugen": ja

I'm wondering why this extension is needed? And if it could cause problems to an existing bootstrap installation or "Premium Contao Themes - Eclipse".

Thank you.

**Comment by fatcrobat** [comment]
Hey there. We already prepared a new version of member_plus without contao-bootstrapper requirement. Will be suggest than. Release next week.
