### ISSUE TITLE
incompatible zu PHP 8

### ISSUE THREAD

**Issue by srhinow** [heimrichhannot/contao-member_plus#8]
Da die require noch auf php: ~5.4 || ~7.0 steht, gibt es eine Meldung wenn man den composer updatet und PHP 8.1 installiert hat: 
```
  Problem 1
    - Root composer.json requires heimrichhannot/contao-member_plus ^2.2 -> satisfiable by heimrichhannot/contao-member_plus[2.2.0, ..., 2.2.4].
    - heimrichhannot/contao-member_plus[2.2.0, ..., 2.2.4] require php ~5.4 || ~7.0 -> your php version (8.1.3) does not satisfy that requirement.
```
Bitte überprüfen ob das Paket auch für PHP 8.1 lauffähig ist und dieses dann in der composer.json freigeben.

**Comment by koertho** [comment]
Ich möchte auf die Readme aufmerksam machen: 

> This bundle is abandoned and not actively maintained anymore. 

Du kannst dir gerne https://github.com/heimrichhannot/contao-advanced-member-bundle oder https://github.com/heimrichhannot/contao-member-bundle anschauen. Dieses Bundle hier wird maximal noch im Rahmen älterer Projekte um das nötigste aktualisiert. 

Welche Funktionen des Modules setzt ihr ein? Eventuell könnte man sowas dann in das Advanced Member Bundle portieren. Du darfst das Modul auch gerne in PHP 8 testen und wenn es soweit passt, einen Pull Request machen.
