### ISSUE TITLE
Dependencies update needed

### ISSUE THREAD

**Issue by JessesNei** [heimrichhannot/contao-member_plus#9]
Contao 4.9
PHP 7.4

Package heimrichhannot/contao-fieldpalette is abandoned, you should avoid using it. Use heimrichhannot/contao-fieldpalette-bundle instead.

**Comment by koertho** [comment]
Please mind the readme:

> This bundle is abandoned and not actively maintained anymore.

What is the reason/feature why you're using this bundle?

**Comment by koertho** [comment]
P.S.: If you want to surpress this notice, you can install https://github.com/heimrichhannot/contao-fieldpalette-bundle, which replaces contao-fieldpalette

**Comment by JessesNei** [comment]
Oh sorry, I really didn't see that.

I think I just added it for some extra fields in the member's palette f.e. the image.

**Comment by koertho** [comment]
In this case I would suggest using https://github.com/heimrichhannot/contao-advanced-member-bundle or add the needed fields in your project dca.
